services:
  savr:
    build:
      context: ../
      dockerfile: web/Dockerfile
    volumes:
      - $DATA_DIR:/data_dir
    environment:
      NODE_ENV: production
      DATA_DIR: /data_dir
    container_name: savr
    restart: always
    ports:
      - 8080:8080
